### PR TITLE
First release of camViz tool

### PR DESCRIPTION
**Pull request by pankhurivanjani**
Solves [#1 ](https://github.com/JdeRobot/camViz/issues/1) and [#2 ](https://github.com/JdeRobot/camViz/issues/2). 

This PR aims to submit the new version of purely rosified camViz tool.

### CODE REVIEW

**Comment by igarag** [comment]
Hi @pankhurivanjani  I'm Nacho. One of JdeRobot's collaborators.

I've been reviewing the Pull Request you've made about the CamViz documentation and I wanted, first of all, to congratulate you for having done it so quickly. In this way we already have a first approach to the documentation of this repository. 

I replicated your repository to see the result before the merge and it seems that the cover is missing content. Since this is the first time we include this template in a repository, it will be the test for future ones :-)

In the test, I configured Front Matter of `/_pages/home.md` as follows:

```
---
permalink: /
header:
  overlay_color: "#5e616c"
  overlay_image: /assets/images/cover/test_header_shear_3.png
  actions:
    - label: "<i class='fas fa-download'></i> Install now"
      url: "&lt;font color=#38B0DE&gt;-==- Proudly Presents
excerpt: 
---
```

The result can be seen in the image.

Screenshot_20190918_185637

Maybe if we added more text in the white space below plus an image of the project and the video that you put in the installation we can better fill the cover of the project, what do you think? 

If you like, we make these small changes and publish it like this.

**Comment by pankhurivanjani** [comment]
Hello @igarag !
Thank you for appreciation and suggestions. I have updated the docs and content. The home page looks better now. Also as suggested by @jmplaza I have added a different section for ROS2 release in the documentation.

**Comment by igarag** [comment]
Hello again @pankhurivanjani .

I have reviewed the changes and if they fit me more. 

I centered the image (with a "trick" that comes inside the minimal mistake's template) and removed the "info" section that I think didn't make much sense on its own.

The changes have been to the `/_pages/home.md` file. From the beginning of the file to section 1. ROS1, it would be like this:


```
---
layout: splash
permalink: /
header:
  overlay_color: "#5e616c"
  overlay_image: /assets/images/cover/test_header_shear_3.png
  actions:
    - label: "<i class='fas fa-download'></i> Install now"
      url: "/installation/"
excerpt:
  Use camViz tool
---
# What is CamViz?

This is a visualization tool, concerned with the client side. CamViz takes image from Pubisher, sends it to GUI (it has it’s own Gtk based GUI), and displays the continous stream of images. It can be used to take images from USB-cam as well as camera attached on a Robot.

![](/assets/images/camvizdocs.png){: .align-center}

Currently this tool is available in two branches:

1. ROS1
```

If you like, we can integrate them like this. I like the rest of the components (installation and ROS section in the navigation bar):-)

In next videos, you can use the open source software:
- [OBSStudio](https://obsproject.com/es/download).
- [Simple Screen Recorder](https://www.maartenbaert.be/simplescreenrecorder/), very popular on Linux. The installation is really easy: `sudo apt-get install simplescreenrecorder`

The reason for recommending this software is to increase the resolution in the videos to FullHD, since the text in the video looks a little blurred. It won't let me use 1080p quality.

I'm sorry for so much text, it's for trying to keep a course as fixed as possible for the documentation of the Software. Great job and thanks for the dedication and effort ;-)

Nacho.

**Comment by pankhurivanjani** [comment]
Hello @igarag , 

Thank you for the review. 

I will update the changes after 5th October. 

About the video quality, I also felt the blurred text an issue. I am currently using Simple Screen Recorder but this. The colcon build takes time to build in ROS1 as well as ROS2. Due to which the video extended to 4-5 minutes.  I was suggested to keep it in 1-2 min time limit. So, while processing the video via online editor the quality of the video is degrading. 

So, maybe we can avoid the time limit thing here?

**Comment by igarag** [comment]
Ooohh, i see.

Hmm, another option is to edit the video. In [this link](https://itsfoss.com/best-video-editing-software-linux/) are the 9 most used editors for Linux (especially the first 4). You can record the video with SimpleScreenRecorder and in the part of the installation that takes more time, accelerate it with a 4x, for example. How do you see it?

Nacho.

**Pull request merged**
